### PR TITLE
Android 13 support hotfix

### PR DESCRIPTION
**Pull request by fluxc**
Added fix for Android 13 request permission

### CODE REVIEW

**Comment by fredriksthlm** [comment]
Is this finnaly verified and works fine for Android13 now? No crashes anymore.
Do you use this in production @fluxc ?

**Comment by fluxc** [comment]
Yes is working fine in production for me.

**Comment by vladansaracpv** [comment]
Any merge/release date for this? Deadline  is closing in :)

**Review by tudordumitriu — APPROVED** [review]

**Comment by jacobg** [comment]
The plugin needs to implement onRequestPermissionResult in order to callback into the web code and resolve the requestPermission() promise.

**Comment by chemerisuk** [comment]
Fixed in v8.

**Pull request closed without merging**
